### ISSUE TITLE
Authenntication error

### ISSUE THREAD

**Issue by waghanza** [ToMesto/cdn77#1]
Hi,

Try to get my account details, I havc an authentication failure

``` ruby
Cdn77::Configuration.new(:login => EMAIL, :password => PASSWORD)
cdn = Cdn77.cdn(config)
```

I'm trying

``` ruby
cdn.get("account", "details")
```

and I have this

``` ruby
Cdn77::MethodCallError: Authentication failed. Please, login again or contact our support.
```

**Comment by waghanza** [comment]
I've found the solution, I have to use a **token** instead of my account password

Obtaining it here
https://client.cdn77.com/account/api

Should not in be in the documentation ?

**Comment by kimrgrey** [comment]
@waghanza, hi! Thank you for your feedback!  I think it's definitely good idea to clarify this fact in README. PR with such changes are totally welcome! May be it's also be good to have a synonym for a parameter `password` to avoid such misunderstanding in the future. WDYT?

**Comment by waghanza** [comment]
@kimrgrey I think `cdn77` **gem** is not what I need.
Obviously it's only a wrapper (you need to read cdn77 api to use it).

**Comment by kimrgrey** [comment]
@waghanza, sure.
